apiVersion: v1
kind: ConfigMap
metadata:
  name: jobhunter-config
  namespace: {{ .Values.namespace }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: {{ .Values.postgres.port | quote }}
  DATABASE_NAME: {{ .Values.postgres.database | quote }}
