apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: job-hunter
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn }}
