apiVersion: v1
kind: ConfigMap
metadata:
  name: jobhunter-config
  namespace: job-hunter
data:
  ENVIRONMENT: "production"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "jobhunter"
