# Namespace
namespace: job-hunter

# Backend configuration
backend:
  image:
    repository: ewiabeng23/job-hunter-backend
    tag: latest
    pullPolicy: Always
  replicas: 2
  port: 8001
  irsaRoleArn: "arn:aws:iam::905846954342:role/job-hunter-backend-role"
  env:
    databaseUrl: ""
    secretKey: "REPLACE_WITH_REAL_SECRET"
    anthropicApiKey: "REPLACE_WITH_REAL_KEY"

# Frontend configuration
frontend:
  image:
    repository: ewiabeng23/job-hunter-frontend
    tag: latest
    pullPolicy: Always
  replicas: 2
  port: 80

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: "16"
  replicas: 1
  port: 5432
  database: jobhunter
  user: jobhunter_user
  password: ""
  storage: 5Gi

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  nodePort: 31678

# Resource limits
resources:
  backend:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  frontend:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  postgres:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
